In [1]:
import numpy as np


In [2]:
# Scenario 1

a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a1+a2



array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [4]:
# Scenario 2
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)
print (a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [5]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

## Broadcasting in NumPy

**Definition:**  
Broadcasting in NumPy refers to the ability of the library to perform arithmetic operations on arrays of **different shapes and sizes**.  
When operating on two arrays, NumPy automatically **stretches the smaller array** along dimensions with size `1` so that both arrays have compatible shapes — **without actually copying data**.  
This makes element-wise operations efficient and memory-friendly.

### Broadcasting Rules:
1. NumPy compares array shapes **element-wise from the last dimension**.
2. Two dimensions are compatible when:
   - They are **equal**, or  
   - One of them is **1**.
3. If dimensions are incompatible, NumPy raises a `ValueError`.



In [7]:
# If x=m and y=n, operation will take place
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [10]:
# If x=1 and y=n then also operation will perform(Same Dimension)

a5=np.arange(3).reshape(1,3)
a6=np.arange(12).reshape(4,3)

print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
a5+a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [12]:
# Dissmilar then what we have to do 
# if x=1 and y!=n then also operation will not take place
a9 = np.arange(3).reshape(1,3)
a10 = np.arange(16).reshape(4,4)
print(a9)
print(a10)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
a9+a10

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [14]:
# If x=1 and n=1 and y==m, operation will take place
a11 = np.arange(3).reshape(1,3)
a12 = np.arange(3).reshape(3,1)
print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [15]:
a11+a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
# If they are of diffferernt dimensiomns
a15= np.arange(4)
a16= np.arange(20).reshape(5,4)
print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [17]:
a15+a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])