In [100]:
import numpy as np

In [101]:

np.random.random()

0.8352424606296812

Seed Function : If I use the seed function we get the same random value again and again

In [102]:
np.random.seed(1)

In [103]:
np.random.random()

0.417022004702574

Uniform : Same random number in a given range

In [104]:
np.random.uniform(1,100)

72.31212485077366

In [105]:
np.random.uniform(1,100,10).reshape(2,5) # in order to generaate random values in an array

array([[ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093],
       [35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054]])

In [106]:
 np.random.randint(1,10,15).reshape(3,5)

array([[3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9]], dtype=int32)

Some Operaations :


In [107]:
a=np.random.randint(1,10,8)
a

array([4, 9, 8, 4, 7, 6, 2, 4], dtype=int32)

In [108]:
np.max(a)

np.int32(9)

In [109]:
np.min(a)

np.int32(2)

In [110]:
[np.argmax(a)] # gives the index of the max value

[np.int64(1)]

In [111]:
np.argmin(a)

np.int64(6)

In [112]:
a=np.random.randint(1,10,8)
a

array([5, 9, 2, 5, 1, 4, 3, 1], dtype=int32)

In [113]:
a[a%2==1]=-1
a
#This will change all the odd to -1


array([-1, -1,  2, -1, -1,  4, -1, -1], dtype=int32)

In [114]:
a=np.random.randint(1,50,12)
a

array([ 5, 26, 48, 35, 24,  8, 27, 26, 41, 23, 10,  4], dtype=int32)

In [115]:
a[a%2==1]=-1

a

array([-1, 26, 48, -1, 24,  8, -1, 26, -1, -1, 10,  4], dtype=int32)

In [116]:
a=np.random.randint(1,50,12)
a

array([40, 24, 37, 28, 38, 20, 39,  9, 33, 35, 11, 24], dtype=int32)

In [117]:
np.where(a%2==1,-1,a)
# This is a one line code which is used to change the numbers we have used it above just a function

array([40, 24, -1, 28, 38, 20, -1, -1, -1, -1, -1, 24], dtype=int32)

Benifit : This function will not change the original array 
It just only displays the values we have given in the arguements

In [118]:
a
# original array wiill remain intact

array([40, 24, 37, 28, 38, 20, 39,  9, 33, 35, 11, 24], dtype=int32)

In [119]:
out=np.where(a%2==1,-1,a)
out

array([40, 24, -1, 28, 38, 20, -1, -1, -1, -1, -1, 24], dtype=int32)

In [125]:
a=np.random.randint(1,50,10)
a

array([24,  2, 14,  4,  1, 14,  7, 22,  7,  3], dtype=int32)

In [143]:
a=np.sort(a)
a

array([ 1,  2,  3,  4,  7,  7, 14, 14, 22, 24], dtype=int32)

In [145]:
a=np.sort(a)[::-1]
a


array([24, 22, 14, 14,  7,  7,  4,  3,  2,  1], dtype=int32)

### 🧮 `numpy.percentile()` — Short Notes

**Definition:**  
The `numpy.percentile()` function calculates the **value below which a given percentage of data** in a dataset falls.

**Syntax:**  
```python
import numpy as np

data = [10, 20, 30, 40, 50]
p = np.percentile(data, 40)
print(p)   # Output: 26.0 (40th percentile)

#numpy.percentile() batata hai — "kitne percent data ke neeche koi particular value aati hai."
#40 peercent elements are less than 26.0


In [122]:
np.percentile(a,25)


np.float64(18.0)

In [123]:
np.percentile(a,50)

np.float64(25.5)

In [124]:
np.percentile(a,99.8)
# you are less than 100percentage of the data
# you are more than 99.8 percentage of the data

np.float64(47.982)