In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])


In [3]:
arr1+arr2 #adds corresponding elements from each array

array([ 5,  7,  9, 11, 13, 15])

In [4]:
arr1-arr2 #difference corresponding elements from each array



array([-3, -3, -3, -3, -3, -3])

In [5]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [10]:
(arr1/2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [11]:
arr2>3 # Check corresponding elements and checks the array 

array([ True,  True,  True,  True,  True,  True])

In [12]:
arr1>3

array([False, False, False,  True,  True,  True])

In [13]:
# Dot product in matrix 
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [14]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
arr3.dot(arr4)
# Matrix multiplication standard is used here 

array([[ 28,  31],
       [100, 112]])

In [17]:
arr1.dot(arr2)

np.int64(154)

In [19]:
arr1.dot(arr3) # order doesnot matches in matrix multiplication

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [20]:
arr4.max()

np.int64(11)

In [21]:
arr4.min(axis=0)
# minimum in coloumwise


array([6, 7])

In [22]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [23]:
arr4.sum()

np.int64(51)

In [24]:
arr4.sum(axis=0)

array([24, 27])

In [25]:
arr4.sum(axis=1)

array([13, 17, 21])

In [26]:
arr4.mean()

np.float64(8.5)

In [27]:
arr4.mean(axis=0)

array([8., 9.])

In [28]:
arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [29]:
arr4.std()

np.float64(1.707825127659933)

In [30]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [31]:
np.median(arr4)

np.float64(8.5)

In [34]:
np.median(arr4)

np.float64(8.5)

In [35]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [36]:
np.log(arr4)

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [37]:
np.log(np.exp(arr4))

array([[ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]])